version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers # Переконайся, що ця мережа визначена в твоєму основному docker-compose.yaml
    depends_on:
      # Важливо, щоб сервіси були не просто запущені, а готові приймати з'єднання.
      # condition: service_healthy краще, якщо для сервісів визначено healthcheck.
      # Якщо ні, то service_started, і в тесті потрібна буде затримка або механізм retry.
      balancer:
        condition: service_started # Або service_healthy
      server1:
        condition: service_started # Або service_healthy
      server2:
        condition: service_started # Або service_healthy
      server3:
        condition: service_started # Або service_healthy
    environment:
      # Ця змінна використовується в тесті для його активації
      INTEGRATION_TEST: "true"
      # Адреса балансувальника для тестів (внутрішня мережа Docker)
      # Балансувальник слухає порт 8080 всередині контейнера згідно з balancer.go
      BALANCER_ADDR: "http://balancer:8080"

  balancer:
    # Передаємо прапорець -trace=true, щоб балансувальник додавав заголовок lb-from
    # Переконайся, що бінарний файл називається 'lb' у твоєму Dockerfile (якщо ENTRYPOINT ["./entry.sh", "lb"])
    # або зміни 'lb' на правильну назву бінарного файлу балансувальника.
    # Якщо твій balancer.go компілюється в бінарник з іншою назвою (наприклад, 'main' або 'balancer'),
    # використовуй цю назву тут. У шаблоні це зазвичай 'lb'.
    command: ["lb", "-trace=true"]
    # Інші налаштування для балансувальника (наприклад, порти) успадковуються з основного docker-compose.yaml
    # і тут їх перевизначати не потрібно, якщо тільки немає специфічної потреби для тестів.
