# docker-compose.test.yaml

# Атрибут version застарів, його можна видалити.

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test # Переконайтеся, що цей файл існує і налаштований
    networks:
      - app_net # Використовуємо мережу, визначену в основному docker-compose.yaml
    depends_on:
      db:
        condition: service_started
      balancer:
        condition: service_started
      server1: # Ці сервіси мають бути визначені в основному docker-compose.yaml
        condition: service_started
      server2:
        condition: service_started
      server3:
        condition: service_started
    environment:
      INTEGRATION_TEST: "true"
      BALANCER_ADDR: "http://balancer:8080"
      TEAM_NAME_FOR_TEST: "duo"
      # DB_SERVICE_URL: "http://db:8081/db" # Якщо потрібно тестам

# Мережа app_net вже має бути визначена в docker-compose.yaml
# Якщо ні, її потрібно визначити тут:
# networks:
#   app_net:
#     external: true # Якщо вона створена основним файлом
# Або визначити її повністю, якщо test.yaml запускається ізольовано і має її створити.
# Для команди docker-compose -f file1 -f file2 ... визначення з file1 будуть доступні.